### ISSUE TITLE
"Views"/'partials" in the functions.php?

### ISSUE THREAD

**Issue by AlchemyUnited** [nicolas-van/wordpress-simple-bootstrap#2]
nice theme. very clean and straight forward. however...

fwiw, functions like simple_bootstrap_display_post_meta(), simple_boostrap_display_post() and such would make more sense as template parts.

You could also use the get_template_part() functionality/hierarchy to make child theme'ing and dev in general much more sensible. For example, post might do gtp(meta, post) and pages might do  gtp(meta, page) but unless meta-post.php and/or page-meta.php were defined each would default to the meta.meta template. The point is, you'd have done what you've done (i.e., the same meta partial for both) but with a much more child-friendly "hook" for modifications.  

As it is, you've kinda "hardcode" things instead of using the magic of get_template_part() 

That sucking sound you hear is my weekend going down the toilet :(

**Comment by nicolas-van** [comment]
Reporting issues on github explaining how things could be improved is good. Making a merge proposal to propose a concrete solution is better.

So if you know what you're doing I encourage you to fork the repository, bring your modifications and create that merge proposal. If the code is clean and it's a real improvement regarding code quality I'll eventually merge it and those features will be available in the next version.

**Comment by AlchemyUnited** [comment]
@nicolas-van - what you're suggesting is more or less - in my eyes - a complete refactoring. 

that said, i'll fork it / submit the pull request so you can see what i mean. 

i have to say, we're pretty disappointed. i would have never expected this (i.e., ! best practice.) unfortunately, the client is already sold on the idea / theme. let's just hope their needs don't require extensive reworkings. 

fwiw, this is a alpha / beta of our framework. 

https://github.com/WPezBoilerStrap/wp-ezboilerstrap-dos

it reflects our mindset on WP theme'ing :)

**Comment by nicolas-van** [comment]
Hu? Man, I'm not suggesting anything. You are suggesting an improvement for this open source project, and I'm explaining you that I don't have time to implement features I don't need but I would agree to review a merge proposal if you are willing to make one. That's just how open source projects work: people contributing to make something useful.

Also, it's completely pointless to tell me about your weekend or your clients because, honestly, I don't care. It's not that I'm insensitive or something like that but I don't know you. You're not a friend of mine, you're not one of my clients, you're not even identified as an individual according to your github account. So there's really not any kind of compassion anyone could have here. I simply don't care because no one would care in a similar situation.

So, please, if you are willing to contribute to this open source project you can do so by using the normal procedures everyone uses on github. If you want to find someone to solve your life problems for free then this is not the place.
