### ISSUE TITLE
Simple Bootstrap

### ISSUE THREAD

**Issue by scottorino** [nicolas-van/wordpress-simple-bootstrap#6]
Nicolas,

I am writing because my website uses your theme, Simple Bootstrap as the parent theme.  I was prompted to update Simple Bootstrap from version .9 to version 2.05.  But when I updated Simple Bootstrap, it broke my site... the menu disappeared, the text appeared different and some of the modules didn’t work.  It took some time to isolate the cause of the issue, but it is definitely the upgrade of the theme and is repeatable.

Is this an issue that other users are experiencing as well?

Thank you,

Scott

**Comment by nicolas-van** [comment]
Hello.

This project uses what is called [semantic versioning](https://github.com/nicolas-van/wordpress-simple-bootstrap/blob/master/readme.txt). Concretely when I update the first number in the version (going from 1.x.x to 2.x.x as example) it means I introduced breaking changes that do not allow backward compatibility. Here, for the version 2.0.0, I ported to Bootstrap version 4 [as stated in the changelog](https://github.com/nicolas-van/wordpress-simple-bootstrap/blob/master/readme.txt) which is indeed a big breaking change by itself.

I know that Wordpress do not care about semantic versioning and will always propose you to update all themes to the latest version regardless of breaking changes. Depending on the point of view this could be interpreted as an error in the conception of Wordpress. Anyway that's how it works and this behavior implies that Wordpress website administrators be very careful when updating a theme with additional customization (like child theme in your case).

So in your case the answer is straightforward: you should not use the 2.x.x version and use the latest version using Bootstrap 3, which is the 1.0.1 version (I can confirm it's compatible with the 0.9 version you were using). I intend to continue supporting the 1.x.x version regarding bug fixing anyway for people still using it.

I'll close this issue since this is technically the answer to you question. But if you have trouble downgrading to version 1.0.1 just add it to this post and I'll find a way to simplify downloading of older versions.

**Comment by nicolas-van** [comment]
Just changed my mind. Since it was not very easy to download a past version I added some script to publish releases on the [Github releases page of the project](https://github.com/nicolas-van/wordpress-simple-bootstrap/releases).

So now you can just download version 1.0.2 and you should be OK.

**Comment by scottorino** [comment]
Nicolas,

Thank you for your thorough response.  I appreciate your taking the time.

I am a little nervous about having an older version of a theme or plugin on my webstie, for security reasons.  Do you ever do side work on websites?  Can I make it worth your while to solve the theme problem on www.filley.com <http://www.filley.com/>? 

Thank you,

Scott Filley

**Comment by nicolas-van** [comment]
You don't have to fear security issues regarding older versions of this theme. As I explained I still support the 1.x version as if there was any bug or problem I would publish new 1.x versions. Also tbere is almost no possibility of security issue with a normal wordpress theme like this one, they just don't interact with the database or that kind of things. You're right about plugins but with most themes it's not necessary.

Regarding hiring me it's possible. We can discuss this on LinkedIn.
